// <auto-generated />
namespace Green.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PatientSurvey1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PatientSurvey1));
        
        string IMigrationMetadata.Id
        {
            get { return "201911220617012_PatientSurvey1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
